more reacting to CI runs

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -70925,6 +70925,9 @@ printf "%s\n" "#define USABLE_SIGIO 1" >>confdefs.h
 
     fi
   fi
+else
+  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: skipping test for usable SIGIO due to missing usable FIONREAD" >&5
+printf "%s\n" "$as_me: skipping test for usable SIGIO due to missing usable FIONREAD" >&6;}
 fi
 
 case ${opsys} in
@@ -70974,17 +70977,17 @@ LDFLAGS="${REAL_LDFLAGS}"
 LIBS="${REAL_LIBS}"
 
 if test "x${CFLAGS}" != "x"; then
-  test -n "${CFLAGS}" && echo "CFLAGS have been replaced with REAL_CFLAGS and are now: ${CFLAGS}"
+  test -n "${CFLAGS}" && echo "CFLAGS have been replaced with REAL_CFLAGS and are now: '${CFLAGS}'"
 else
   test -z "${CFLAGS}" && echo "uh oh, overriding CFLAGS with REAL_CFLAGS made it empty..."
 fi
 if test "x${CPPFLAGS}" != "x"; then
-  test -n "${CPPFLAGS}" && echo "CPPFLAGS have been replaced with REAL_CPPFLAGS and are now: ${CPPFLAGS}"
+  test -n "${CPPFLAGS}" && echo "CPPFLAGS have been replaced with REAL_CPPFLAGS and are now: '${CPPFLAGS}'"
 else
   test -z "${CPPFLAGS}" && echo "uh oh, overriding CPPFLAGS with REAL_CPPFLAGS made it empty..."
 fi
 if test "x${LDFLAGS}" != "x"; then
-  test -n "${LDFLAGS}" && echo "LDFLAGS have been replaced with REAL_LDFLAGS and are now: ${LDFLAGS}"
+  test -n "${LDFLAGS}" && echo "LDFLAGS have been replaced with REAL_LDFLAGS and are now: '${LDFLAGS}'"
 else
   test -z "${LDFLAGS}" && echo "uh oh, overriding LDFLAGS with REAL_LDFLAGS made it empty..."
 fi
@@ -74263,7 +74266,7 @@ fi
 if test "x${with_features}" = "xno" && test "x${enable_acl}" != "xyes"; then
   enable_acl=no
 elif test "x${enable_acl}" != "xno" && test "x${ac_cv_func_acl_delete_def_file}" = "x"; then
-  test -z "${ac_cv_func_acl_delete_def_file}"
+  test -z "${ac_cv_func_acl_delete_def_file}" && echo "need manual check for acl_delete_def_file..."
   ac_fn_c_check_func "$LINENO" "acl_delete_def_file" "ac_cv_func_acl_delete_def_file"
 if test "x$ac_cv_func_acl_delete_def_file" = xyes
 then :
@@ -74271,6 +74274,11 @@ then :
 
 fi
   ## might want to do this somewhere else...
+fi
+
+if test "x${enable_acl}" != "xno" && test "x${ac_cv_func_acl_delete_def_file}" != "xyes"; then
+  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: WARNING: building with ACLs enabled requires the acl_delete_def_file function; this build will probably fail (see POSIX 1003.1e draft 17)" >&5
+printf "%s\n" "$as_me: WARNING: building with ACLs enabled requires the acl_delete_def_file function; this build will probably fail (see POSIX 1003.1e draft 17)" >&2;}
 fi
 
 # Configure gnulib. Although this does not affect CFLAGS or LIBS
@@ -78913,8 +78921,8 @@ rm -f core conftest.err conftest.$ac_objext conftest.beam \
         LIBS=$save_LIBS
         test $gl_pthread_api = yes && break
       done
-      echo "$as_me:78916: gl_pthread_api=$gl_pthread_api" >&5
-      echo "$as_me:78917: LIBPTHREAD=$LIBPTHREAD" >&5
+      echo "$as_me:78924: gl_pthread_api=$gl_pthread_api" >&5
+      echo "$as_me:78925: LIBPTHREAD=$LIBPTHREAD" >&5
 
       gl_pthread_in_glibc=no
       # On Linux with glibc >= 2.34, libc contains the fully functional
@@ -78940,7 +78948,7 @@ rm -rf conftest*
 
           ;;
       esac
-      echo "$as_me:78943: gl_pthread_in_glibc=$gl_pthread_in_glibc" >&5
+      echo "$as_me:78951: gl_pthread_in_glibc=$gl_pthread_in_glibc" >&5
 
       # Test for libpthread by looking for pthread_kill. (Not pthread_self,
       # since it is defined as a macro on OSF/1.)
@@ -79118,7 +79126,7 @@ fi
 
         fi
       fi
-      echo "$as_me:79121: LIBPMULTITHREAD=$LIBPMULTITHREAD" >&5
+      echo "$as_me:79129: LIBPMULTITHREAD=$LIBPMULTITHREAD" >&5
     fi
     { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking whether POSIX threads API is available" >&5
 printf %s "checking whether POSIX threads API is available... " >&6; }
